require 'visimp' {
  languages = {
    -- 'agda',
    -- 'ampl',
    -- 'bash',
    -- 'c',
    -- 'coq',
    -- 'csharp',
    -- 'css',
    -- 'dart',
    -- 'gleam',
    -- 'go',
    -- 'haskell',
    -- 'hcl',
    -- 'html',
    -- 'idris',
    -- 'java',
    -- 'javascript',
    -- 'json',
    -- 'kotlin',
    -- 'latex',
    -- 'lean',
    -- 'lua',
    -- 'markdown'
    -- 'ocaml',
    -- 'php',
    -- 'prolog',
    -- 'python',
    -- 'rust',
    -- 'svelte',
    -- 'swift',
    -- 'toml',
    -- 'typst',
    -- 'vue'
  },

  theme = {
    package = 'gruvbox-community/gruvbox',
    colorscheme = 'gruvbox',
    background = 'dark',
    lualine = 'gruvbox',
  },
}
